extends Node2D

enum SquareState {NORMAL, X_MARKED, O_MARKED, REVEALED, FADING_BLUE_LINES, BLUE_LINES, BOTTOM_BLUE_LINES, 
				  BOTTOM_FADING_BLUE_LINES, SIDE_FADING_BLUE_LINES, SIDE_BLUE_LINES, SIDE_BOTTOM_BLUE_LINES, 
				  SIDE_BOTTOM_FADING_BLUE_LINES, REVEALED_X, BLANK}
enum RowDirection {ROW, COLUMN}
